workflows:
  my-workflow:
    name: Build APK Downloader Ngebut
    instance_type: mac_mini_m1
    scripts:
      - name: Install Dependencies & Cython
        script: |
          pip install --upgrade pip
          pip install setuptools Cython==0.29.33 buildozer
      - name: Force Install Aidl & Build-Tools
        script: |
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools"
      - name: Build APK (Fixing Aidl Path)
        script: |
          # Mantra rahasia: kasih tahu Buildozer di mana Aidl berada
          export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/33.0.0
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          buildozer android debug
    artifacts:
      - bin/*.apk
