workflows:
  my-workflow:
    name: Build APK Downloader Ngebut
    instance_type: mac_mini_m1
    scripts:
      - name: Install Dependencies
        script: |
          pip install --upgrade pip
          pip install setuptools Cython==0.29.33 buildozer
      - name: Accept Licenses & Install Build-Tools
        script: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      - name: Build APK
        script: |
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          buildozer android debug
    artifacts:
      - bin/*.apk
