name: Build APK Anti Gagal
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer
      - name: Build APK (Auto-Accept SDK)
        run: |
          # Perintah sakti buat bikin file spec otomatis kalau belum ada
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          # Langsung hajar build
          yes | buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Downloader-Ngebut-Final
          path: bin/*.apk
